language: cpp
jobs:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      script:
        - sudo apt-get install pkg-config libglfw3-dev
        - cd deb_tools
        - bash auto-build.sh
    - os: linux
      dist: xenial
      compiler: clang
      script:
        - sudo apt-get install pkg-config libglfw3-dev
        - cd deb_tools
        - bash auto-build.sh
    - os: osx
      osx_image: xcode10.2
      script:
        - brew install glfw3
        - cd mac_tools
        - bash auto-build.sh