#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]}"
while [ -L "$SCRIPT_PATH" ]; do
    SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" && pwd)"
    SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
    [[ "$SCRIPT_PATH" != /* ]] && SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH"
done
WIX_DIR="$(cd -P "$(dirname "$SCRIPT_PATH")" && pwd)"
REPO_ROOT="$(cd "$WIX_DIR/../.." && pwd -P)"

cleanup() {
    rm -f "$REPO_ROOT/build/icon.ico" "$REPO_ROOT/build/license.rtf" "$WIX_DIR/Product.wxs"
    rm -rf "$WIX_DIR/wix_build"
}
trap cleanup EXIT

# Prefer the default WiX install path when available.
WIX_DEFAULT_BIN="/c/Program Files (x86)/WiX Toolset v3.11/bin"
if [ -d "$WIX_DEFAULT_BIN" ]; then
    export PATH="$WIX_DEFAULT_BIN:$PATH"
fi

if ! command -v candle >/dev/null 2>&1 || ! command -v light >/dev/null 2>&1; then
    echo "WiX tools (candle/light) were not found in PATH." >&2
    exit 1
fi

cd "$WIX_DIR"

# Remove stale temporary artifacts from previous interrupted runs.
cleanup

cp -f ./icon.ico "$REPO_ROOT/build/icon.ico"
cp -f ./license.rtf "$REPO_ROOT/build/license.rtf"

CS_BIN="$REPO_ROOT/build/bin/cs"
CS_IMPORTS="$REPO_ROOT/build/imports"

CSVER="$($CS_BIN -i "$CS_IMPORTS" ./get_csver.csc | tr -d '\r\n')"
CANDLE_ARGS="$($CS_BIN -i "$CS_IMPORTS" ./candle_args.csc | tr -d '\r\n')"

echo "CovScript Runtime Version: $CSVER"
echo "Candle Arguments: $CANDLE_ARGS"

$CS_BIN -i "$CS_IMPORTS" ./gen_wxs.csc ./wxs_template.xml

mkdir -p "$WIX_DIR/wix_build"
cd "$WIX_DIR/wix_build"
# CANDLE_ARGS is generated by project script and intentionally split into multiple args.
# shellcheck disable=SC2086
candle $CANDLE_ARGS ../Product.wxs -nologo
light -ext WixUIExtension -b "$REPO_ROOT/build" -cultures:en-us Product.wixobj -out "covscript-$CSVER.msi" -nologo
cp -f "covscript-$CSVER.msi" "$REPO_ROOT/"
