name: schedule

on:
  [push]
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1

      - name: build-ubuntu
        if: matrix.os == 'ubuntu-latest'
        run:
          - cd deb_tools
          - bash auto-build.sh
      
      - name: build-macos
        if: matrix.os == 'macOS-latest'
        run:
          - cd mac_tools
          - bash auto-build.sh

      - uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: covscript-ubuntu
          path: deb_tools/deb-src/*.deb

      - uses: actions/upload-artifact@master
        if: matrix.os == 'macOS-latest'
        with:
          name: covscript-macos
          path: mac_tools/*.dmg