name: schedule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1

      - name: build-ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libglfw3-dev
          mkdir build
          cd deb_tools
          bash auto-build.sh
          cp deb-src/*.deb ../build
      
      - name: test-ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg -i build/*.deb
          cs -v
          cs_dbg -v
          cspkg --list
          cd deb_tools/build-cache/covscript/examples
          cs benchmark.csc
          cs http_request.csc

      - uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: covscript-ubuntu
          path: build