name: schedule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev libcurl4-openssl-dev libglfw3-dev
          bash auto-build.sh
          bash package_tools/deb/make.sh
          cp *.deb covscript-amd64-nightly.deb
      
      - name: Download MinGW-w64
        if: matrix.os == 'windows-latest'
        uses: i3h/download-release-asset@v1
        with:
          owner: covscript-archives
          repo: mingw-w64
          tag: 12.2.0.2
          file: gcc-12.2.0-mingw-w64ucrt-10.0.0-r5-covscript.org.zip
          
      - name: Download Wix Toolset
        if: matrix.os == 'windows-latest'
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
          
      - name: Install Toolset in Windows
        if: matrix.os == 'windows-latest'
        run: |
          rm C:/ProgramData/chocolatey/bin/gcc.exe -force
          rm C:/ProgramData/chocolatey/bin/g++.exe -force
          rm C:/Strawberry/c/bin/gcc.exe -force
          rm C:/Strawberry/c/bin/g++.exe -force
          7z x gcc-12.2.0-mingw-w64ucrt-10.0.0-r5-covscript.org.zip -oC:\
          7z x wix311-binaries.zip -oC:\Wix
          
      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: |
          .github/workflows/build.bat
          cp *.msi covscript-x64-nightly.msi
          
      - name: Run tests on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg -i covscript-amd64-nightly.deb
          cs -v
          cs_dbg -v
          cspkg install --import --yes
          cspkg list
          cs build-cache/covscript/.github/workflows/benchmark.csc
          
      - name: Package CSPKG Repo on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r cspkg-linux-x86_64-nightly.zip cspkg-repo
          
      - name: Package Build files on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r covscript-linux-x86_64-nightly.zip build
          
      - name: Package CSPKG Repo and Build files on Windows
        if: matrix.os == 'windows-latest'
        run: |
          7z a -mmt4 -mx9 cspkg-winucrt-x86_64-nightly.7z cspkg-repo
          7z a -mmt4 -mx9 covscript-winucrt-x86_64-nightly.7z build

      - name: Automatic Release MSI
        if: matrix.os == 'windows-latest'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-schedule"
          title: "Windows Schedule Nightly Build"
          prerelease: true
          files: |
            *.msi
            *.7z
      
      - name: Automatic Release DEB
        if: matrix.os == 'ubuntu-latest'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "ubuntu-schedule"
          title: "Ubuntu Schedule Nightly Build"
          prerelease: true
          files: |
            *.deb
            *.zip
