name: schedule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022 ]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev libcurl4-openssl-dev libglfw3-dev
          bash auto-build.sh
          bash package_tools/deb/make.sh
          cp *.deb covscript-amd64-nightly.deb
      
      - name: Download MinGW-w64
        if: matrix.os == 'windows-2022'
        uses: i3h/download-release-asset@v1
        with:
          owner: covscript-archives
          repo: mingw-w64
          tag: 13.2.0.1
          file: gcc-13.2.0-mingw-w64ucrt-11.0.1-r3-covscript.org.zip
          
      - name: Install Toolset in Windows
        if: matrix.os == 'windows-2022'
        run: |
          mkdir C:\mingw64-covscript
          7z x gcc-13.2.0-mingw-w64ucrt-11.0.1-r3-covscript.org.zip -oC:\mingw64-covscript
          
      - name: Build on Windows
        if: matrix.os == 'windows-2022'
        run: |
          .github/workflows/build.bat
          cp *.msi covscript-x64-nightly.msi
          
      - name: Run tests on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo dpkg -i covscript-amd64-nightly.deb
          cs -v
          cs_dbg -v
          cs build-cache/covscript/.github/workflows/benchmark.csc
          
      - name: Package CSPKG Repo on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r cspkg-linux-x86_64-nightly.zip cspkg-repo
          
      - name: Package Build files on Ubuntu
        if: matrix.os == 'ubuntu-20.04'
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r covscript-linux-x86_64-nightly.zip build
          
      - name: Package CSPKG Repo and Build files on Windows
        if: matrix.os == 'windows-2022'
        run: |
          7z a -mmt4 -mx9 cspkg-winucrt-x86_64-nightly.7z cspkg-repo
          7z a -mmt4 -mx9 covscript-winucrt-x86_64-nightly.7z build

      - name: Automatic Release MSI
        if: matrix.os == 'windows-2022'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "windows-schedule"
          title: "Windows Schedule Nightly Build"
          prerelease: true
          files: |
            *.msi
            *.7z
      
      - name: Automatic Release DEB
        if: matrix.os == 'ubuntu-20.04'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "ubuntu-schedule"
          title: "Ubuntu Schedule Nightly Build"
          prerelease: true
          files: |
            *.deb
            *.zip
