name: schedule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm, macos-14, windows-2022 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          bash misc/base_install_linux.sh
          bash auto-build.sh
          bash package_tools/deb/make.sh
          cp *.deb covscript-ubuntu-$(arch)-nightly.deb
      
      - name: Build on macOS
        if: matrix.os == 'macos-14'
        run: |
          bash misc/base_install_macos.sh
          bash auto-build.sh
          bash package_tools/dmg/make.sh
          cp *.dmg covscript-macos-arm64-nightly.dmg
      
      - name: Download MinGW-w64
        if: matrix.os == 'windows-2022'
        run: |
          gh release download 15.1.0.4 -R covscript-archives/mingw-w64 -p "gcc-15.1.0-mingw-w64ucrt-13.0.0-r4-covscript-org.zip"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Toolset in Windows
        if: matrix.os == 'windows-2022'
        run: |
          mkdir C:\mingw64-covscript
          7z x gcc-15.1.0-mingw-w64ucrt-13.0.0-r4-covscript-org.zip -oC:\mingw64-covscript
          
      - name: Build on Windows
        if: matrix.os == 'windows-2022'
        run: |
          .github/workflows/build.bat
          cp *.msi covscript-windows-x86_64-nightly.msi
          
      - name: Run tests on Ubuntu
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          sudo dpkg -i covscript-ubuntu-$(arch)-nightly.deb
          cs -v
          cs_dbg -v
          cs build-cache/covscript/tests/benchmark.csc

      - name: Package CSPKG Repo and Build files on Ubuntu
        if: matrix.os == 'ubuntu-22.04' || matrix.os == 'ubuntu-22.04-arm'
        run: |
          7z a -mmt4 -mx9 cspkg-ubuntu-$(arch)-nightly.7z cspkg-repo
          7z a -mmt4 -mx9 covscript-ubuntu-$(arch)-nightly.7z build
          
      - name: Package CSPKG Repo and Build files on macOS
        if: matrix.os == 'macos-14'
        run: |
          7z a -mmt4 -mx9 cspkg-macos-arm64-nightly.7z cspkg-repo
          7z a -mmt4 -mx9 covscript-macos-arm64-nightly.7z build
          
      - name: Package CSPKG Repo and Build files on Windows
        if: matrix.os == 'windows-2022'
        run: |
          7z a -mmt4 -mx9 cspkg-windows-x86_64-nightly.7z cspkg-repo
          7z a -mmt4 -mx9 covscript-windows-x86_64-nightly.7z build

      - name: Automatic Release MSI
        if: matrix.os == 'windows-2022' && success()
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "windows-schedule"
          name: "Windows Schedule Nightly Build"
          prerelease: true
          files: |
            *.msi
            *.7z
      
      - name: Automatic Release DEB
        if: matrix.os == 'ubuntu-22.04' && success()
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "ubuntu-schedule"
          name: "Ubuntu Schedule Nightly Build"
          prerelease: true
          files: |
            *.deb
            *.7z
      
      - name: Automatic Release DEB
        if: matrix.os == 'ubuntu-22.04-arm' && success()
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "ubuntu-arm-schedule"
          name: "Ubuntu for ARM Schedule Nightly Build"
          prerelease: true
          files: |
            *.deb
            *.7z
      
      - name: Automatic Release DMG
        if: matrix.os == 'macos-14' && success()
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "macos-schedule"
          name: "macOS Schedule Nightly Build"
          prerelease: true
          files: |
            *.dmg
            *.7z
