name: schedule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libglfw3-dev
          mkdir build
          cd deb_tools
          bash auto-build.sh
      
      - name: Run tests on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo dpkg -i build/*.deb
          cs -v
          cs_dbg -v
          cspkg --list
          cd deb_tools/build-cache/covscript/examples
          cs benchmark.csc
          cs http_request.csc

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "schedule"
          title: "Schedule Build"
          files: |
            deb-src/*.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        if: matrix.os == 'ubuntu-latest'
        with:
          name: covscript-ubuntu
          path: build
